README.md
package-lock.json
package.json

Viper can be launched/built on Windows (`npx` command allows to run a npm package).

fix: Windows

---

src/utils.js

Storing latest downloaded version in viper.json.
Skipping download if latest GitHub version tag equals local value.
Fixes #5.

feat: Updates downloading

---

src/lang/fr.json

Adding French translations.
Layout isn't ready for this though, dunno if I should fix it here or in another PR.

feat: French localisation

---

src/app/main.js
src/index.js
src/lang/en.json
src/lang/fr.json
src/utils.js

Prevents the interface from appearing as long as user didn't select a game path.
Fixes #22.

fix: No game path

---

src/lang/fr.json

Adding missing french translations.

Translations

---

src/lang/fr.json

Adding missing French translations.

i18n: mod support

---

src/lang/en.json
src/lang/fr.json
src/utils.js

If `settings.autoupdate` is `true`, viper will check for Northstar updates every 15 minutes, and will trigger update process if a new release is available.
---

feat: Northstar auto-updates

---

src/app/lang.js
src/app/launcher.js
src/app/main.js
src/cli.js
src/index.js
src/lang.js
src/requests.js
src/utils.js

Currently there's not a lot of documentation in the files, only very few comments, I'll be attempting to fix that here.

Adding documentation/comments

---

src/extras/findgame.js

- os nor app was imported
- returned the entire vdf file instead

Repair vdf reading

---

src/extras/findgame.js
src/utils.js

Game folder is correctly found on Windows if game has been installed through Steam or Origin.

fix: Finding Windows game folder

---

src/app/main.js
src/extras/findgame.js
src/lang/en.json
src/utils.js

What if the user is not running Linux or windows?

Edge case in vdf reading

---

src/lang/fr.json

French translations for toasts

---

src/lang/es.json

Updated localization for toast notifications

---

src/lang/es.json

feat: Spanish "gui.mods.dragdrop" key

---

src/lang/fr.json

feat: French translations

---

src/lang/es.json

New Spanish strings

---

src/lang/fr.json

I'm not sure of the "Wine prefixe" French translation though.

feat: adding French translations

---

src/lang/es.json

Added linux related strings with their respective translations and some corrections.
#116

Add Spanish strings

---

src/lang/es.json

"gui.mods.confirmdependencies" "es" localization

---

README.md

Adding the new minimalistic launcher made by EladNLG to the README.

Added FIITE as launcher

---

src/lang/de.json

This PR contains the german translation for the requested localization in PR https://github.com/0neGal/viper/pull/155

German Translation.

---

src/lang/de.json

German localization for https://github.com/0neGal/viper/pull/157

Error Toasts German Localization.

---

src/lang/fr.json

feat: missing french trads

---

src/lang/de.json

Localization for https://github.com/0neGal/viper/pull/183.
This also fixes a typo that I found.

Support EA Desktop German Localization

---

src/lang/es.json

The text of some elements did not correctly convey their purpose, so they were changed to be better understood. Some spelling mistakes were corrected.

[Spanish Translation] Improve clarity and fix spelling errors in element descriptions

---

src/lang/es.json

Added Spanish strings for plugin install prompt

---

src/lang/es.json

Add missing Spanish localizations

---

src/lang/de.json

Silly little German translation 🕺

i18n: German Translation

---

src/cli.js

ran across these while implementing something else

fix: correct cli ipc event names

---

src/app/js/browser.js

fix: correct install callback for mods that aren't already installed

---

src/lang/zh.json

i18n: update zh translation

---

src/lang/fr.json

https://github.com/0neGal/viper/issues/255

feat: Add french localization

---

src/lang/de.json

Localization for https://github.com/0neGal/viper/issues/255

feat: Add German Localization.
